spring:
  application:
    name: usuario-microservice

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/usuario
    username: user
    password: Uisrael

server:
  port: 0
