spring:
  application:
    name: usuarios-microservice

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5438/productodb
    username: admin
    password: Uisrael

server:
  port: 0