spring:
  application:
    name: usuarios-microservice

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5437/productodb
    username: admin
    password: Uisrael


server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      prefer-ip-address: true
      instance:
        instance-id: ${spring.application.name}:${random.uuid}
